### ISSUE TITLE
NoCredentialsError: Unable to locate credentials

### ISSUE THREAD

**Issue by zhiwenfan** [allenai/objaverse-rendering#4]
Hi, thank you for sharing the wonderful work for processing objaverse dataset. However, I was wondering why the following problem happens. Thanks!
```

(zero123)@ece-a51951:/ssd1/projects/zero123/objaverse-rendering$ python3 scripts/download_objaverse.py --start_i 0 --end_i 100
798759 <class 'list'>
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/ssd1/projects/zero123/objaverse-rendering/scripts/download_objaverse.py", line 57, in <module>
    completed_uids = get_completed_uids()
  File "/ssd1/projects/zero123/objaverse-rendering/scripts/download_objaverse.py", line 29, in get_completed_uids
    bucket_files = [obj.key for obj in tqdm(bucket.objects.all())]
  File "/ssd1/projects/zero123/objaverse-rendering/scripts/download_objaverse.py", line 29, in <listcomp>
    bucket_files = [obj.key for obj in tqdm(bucket.objects.all())]
  File "/ssd1/anaconda3/envs/zero123/lib/python3.9/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/ssd1/anaconda3/envs/zero123/lib/python3.9/site-packages/boto3/resources/collection.py", line 81, in __iter__
    for page in self.pages():
  File "/ssd1/anaconda3/envs/zero123/lib/python3.9/site-packages/boto3/resources/collection.py", line 171, in pages
    for page in pages:
  File "/ssd1/anaconda3/envs/zero123/lib/python3.9/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/ssd1/anaconda3/envs/zero123/lib/python3.9/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/ssd1/anaconda3/envs/zero123/lib/python3.9/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/ssd1/anaconda3/envs/zero123/lib/python3.9/site-packages/botocore/client.py", line 943, in _make_api_call
    http, parsed_response = self._make_request(
  File "/ssd1/anaconda3/envs/zero123/lib/python3.9/site-packages/botocore/client.py", line 966, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/ssd1/anaconda3/envs/zero123/lib/python3.9/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/ssd1/anaconda3/envs/zero123/lib/python3.9/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/ssd1/anaconda3/envs/zero123/lib/python3.9/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/ssd1/anaconda3/envs/zero123/lib/python3.9/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/ssd1/anaconda3/envs/zero123/lib/python3.9/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/ssd1/anaconda3/envs/zero123/lib/python3.9/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/ssd1/anaconda3/envs/zero123/lib/python3.9/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
  File "/ssd1/anaconda3/envs/zero123/lib/python3.9/site-packages/botocore/signers.py", line 189, in sign
    auth.add_auth(request)
  File "/ssd1/anaconda3/envs/zero123/lib/python3.9/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

**Comment by zhiwenfan** [comment]
I have created the aws account and set the correct key/credentials.
However, when I run the download_objaverse.py script, I always encountered the issue:
"botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied"
Any idea could be very thankful.

**Comment by VLadImirluren** [comment]
I encountered when run the distributed.py in download_object function
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

Can you help me ?

**Comment by Aiverson20** [comment]
你好，我也遇到了这个问题，请问您解决了吗？
